### ISSUE TITLE
List of admissible users

### ISSUE THREAD

**Issue by gpetho** [DEpt-metagenom/MetagenoMongo#15]
@laczkol @haalasz @CsongorFreytag 

We're at the point in the application where the validated output csv file needs to be saved to the disk and uploaded to the destination directory. When the file is uploaded, a notification email is sent to an email address.

I suggest that the csv file should be named according to the following format: `{user name}_{YY-MM-DD}_{HH:MM:SS}.csv`, so name of the user who is uploading the file, followed by the current date and time at which the csv file is being generated and uploaded to the destination directory.

The user will enter their user name in the respective field in the UI of the browser application, the application will check whether this user name is included in the list of admissible user names, output an error message ("unknown user") and refuse the upload if the specified user name is not included in the list of admissible users, and add the user name to the file name and proceed with the upload if it is admissible. I think this is the right way to do it. It makes it clear who the data in the csv is coming from and it also introduces a weak form of user authentication as a bonus.

The question is what list of user names should be used for this. There are two obvious options: using either the GitHub or the Keybase identifier column of the list of colleagues here: https://github.com/DEpt-metagenom/CHAT

Should we use either of these, and if so, which one, or a completely different list?

**Comment by laczkol** [comment]
I'm glad to hear that.

> I suggest that the csv file should be named according to the following format: {user name}_{YY-MM-DD}_{HH:MM:SS}.csv, so name of the user who is uploading the file, followed by the current date and time at which the csv file is being generated and uploaded to the destination directory.
\
The user will enter their user name in the respective field in the UI of the browser application, the application will check whether this user name is included in the list of admissible user names, output an error message ("unknown user") and refuse the upload if the specified user name is not included in the list of admissible users, and add the user name to the file name and proceed with the upload if it is admissible. I think this is the right way to do it. It makes it clear who the data in the csv is coming from and it also introduces a weak form of user authentication as a bonus.

Good idea, I support this.

> The question is what list of user names should be used for this. There are two obvious options: using either the GitHub or the Keybase identifier column of the list of colleagues here: [DEpt-metagenom/CHAT](https://github.com/DEpt-metagenom/CHAT)

@CsongorFreytag @haalasz can you imagine these submissions being mentioned in our GitHub repositories, e.g. in project and quality management issues or sequencing run logging issues? If this is the case and corrections are requested in the metadata, it might be more practical to use the GitHub username to name the submitted files, as it would then be very easy to tag the submitter of the metadata. I'm not in favor of using Keybase usernames instead of GitHub usernames, but I'm also not against it if you think it's better for any reason. When we register new users on one of our servers, we use the new user's last name and the first letter of the first name to create the user ID. I see this naming strategy as an alternative that is also easy to follow.

**Comment by CsongorFreytag** [comment]
> Should we use either of these, and if so, which one, or a completely different list?

Yes you can. Use GitHub username, and if is possible allow to save csv without upload.

**Comment by CsongorFreytag** [comment]
I don't know the UX flow, but it is useful if the user name is not entered or is entered incorrectly, so that the table that has already been filled in is not lost, there is less frustration for user, I think.

**Comment by gpetho** [comment]
I see. Saving the table locally is not the right solution for this problem in my opinion, but this is a good point that I have not thought about. What we will do is force the user to enter their user name and verify it before the user opens their input Excel or csv file that they want to validate or before the user can enter a new record (table row) to be validated manually, instead of demanding this before the file is saved. This guarantees that work is never lost.

**Comment by gpetho** [comment]
@iwmstjp I have updated `app.py`, I have added the list of hashed user names to it. I have added a function called `check_user()` which returns True if the user name entered by the user is in the column of GitHub user names in the list of coworkers here: https://github.com/DEpt-metagenom/CHAT
It returns otherwise.

Implement the feature described in the previous comment: When the user tries to either "Import file" or add a new empty row to the table (the button for this is not implemented yet in the version of the application that is covered by the pull request I accepted on Tuesday; I assume you have implemented it since then), then the application should call this function on the (stripped) content of the user name field and output an error message if no user name was specified and a different error message when a user name was specified but is not in the list of known users. In the latter case, the user should contact the database admin.

The deadline for this is today 2 pm, the time we start the usual daily standup meeting. This check should be very easy to implement.

**Comment by gpetho** [comment]
@haalasz  Please join us in this meeting: https://meet.google.com/ptf-aupp-dfu

**Comment by gpetho** [comment]
> I suggest that the csv file should be named according to the following format: `{user name}_{YY-MM-DD}_{HH:MM:SS}.csv`, so name of the user who is uploading the file, followed by the current date and time at which the csv file is being generated and uploaded to the destination directory.

As Masato very correctly noticed, I made a mistake here, the colon character cannot appear in the file name, so instead of `HH:MM:SS` the correct format is `HH-MM-SS`.

**Comment by iwmstjp** [comment]
This issue was resolved by the following commits:
[feature: add user check by hash](https://github.com/iwmstjp/MetagenoMongo/commit/478041ca1043535ea97490b712913fb7263ab00b)
[fix: chech user_name before import files and input forms](https://github.com/iwmstjp/MetagenoMongo/commit/144714d6947c1150727c9884d52b77b376c55bbe)
[fix: change file name format because : in a file path somtime makes errors](https://github.com/iwmstjp/MetagenoMongo/commit/e8613452c3c2ea2a869275870f6da45711f7eb87)
[feature: add user_name and date to a saving file](https://github.com/iwmstjp/MetagenoMongo/commit/a14dcde65dfd806be02da91bbcdae02da9b15cd5)
