### ISSUE TITLE
Make certain columns mandatory and disallow special characters in some cells

### ISSUE THREAD

**Issue by haalasz** [DEpt-metagenom/MetagenoMongo#41]
I had a meeting with @CsongorFreytag  where we reviewed the app. 
- We would like `project_directory` and `projectID` to be **mandatory columns**. The current mandatory columns are `sampleID` and `collection_date` which is fine.
- We also want to **disallow special characters** in `project_directory`, `projectID`, `sampleID` and also in `run_directory` (not mandatory column), with the exception of hyphens and underscores.

In the columns mentioned above, we would like to allow users to use only numbers and letters of the Latin alphabet (lower case, upper case) plus the exceptions.

**Comment by gpetho** [comment]
There is just one thing that I would have done differently from your solution. You are compiling the regex pattern every time the function is called. This is inefficient and unnecessary, since the `re` module caches the compiled versions of string patterns after they have been compiled. It is not documented properly (as far as I know) how this caching works exactly and whether an explicit call of `re.compile` compiles the pattern again or also checks in a cache, like it happens for string patterns. My guess is that it compiles the pattern every time this function is called for a specific string, so this should be avoided. What you should do instead is compile the pattern just once.

One way to do this is to just use the pattern as a string, not as a pattern object, like this:
```
re.search(r'[^a-zA-Z0-9-_]', s)
```
This works because, as I have mentioned, the compiled patterns for a certain undocumented number (but at least 10) of regex strings are cached, so they are only compiled once when a function call using that pattern is first evaluated.

The second possible solution, which is more consistent with the rest of your code, is to put the compilation of the regex pattern on the top level of your module, right after the date pattern is defined. This way the pattern is only compiled once, when the module is imported, nothing else needs to be changed, and you also avoid the uncertainties involved in the not properly documented caching of regex patterns.

Keep this in mind in the future. Compiling a regex pattern is relatively costly, using a compiled pattern to match a string is very fast. The only point of compiling a regex pattern (as well as of the not properly documented caching) is to keep the compilation overhead small.

So there are two good practices in general when using regexes in Python: Either you are using only a few regexes in your whole code, up to 10 or maybe 20, in which case you can just skip the explicit compilation of the regexes and use the matching functions from the `re` module that have pattern strings as arguments. Or you are using many regexes, or just prefer to use the pattern objects from the `re` module instead of pattern strings. In this case, make sure that you compile each pattern only once, ideally when the module is imported.

**Comment by gpetho** [comment]
Closing as resolved.

**Comment by gpetho** [comment]
I corrected the regular expression handling in commit https://github.com/DEpt-metagenom/MetagenoMongo/commit/291fa6e8eeb3db3b259d98e7b06daae61fce65c3
